/*
Daytona Toolbox API

Daytona Toolbox API

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package toolbox

import (
	"encoding/json"
)

// checks if the ListRecordingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRecordingsResponse{}

// ListRecordingsResponse struct for ListRecordingsResponse
type ListRecordingsResponse struct {
	Recordings []Recording `json:"recordings,omitempty"`
}

// NewListRecordingsResponse instantiates a new ListRecordingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRecordingsResponse() *ListRecordingsResponse {
	this := ListRecordingsResponse{}
	return &this
}

// NewListRecordingsResponseWithDefaults instantiates a new ListRecordingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRecordingsResponseWithDefaults() *ListRecordingsResponse {
	this := ListRecordingsResponse{}
	return &this
}

// GetRecordings returns the Recordings field value if set, zero value otherwise.
func (o *ListRecordingsResponse) GetRecordings() []Recording {
	if o == nil || IsNil(o.Recordings) {
		var ret []Recording
		return ret
	}
	return o.Recordings
}

// GetRecordingsOk returns a tuple with the Recordings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRecordingsResponse) GetRecordingsOk() ([]Recording, bool) {
	if o == nil || IsNil(o.Recordings) {
		return nil, false
	}
	return o.Recordings, true
}

// HasRecordings returns a boolean if a field has been set.
func (o *ListRecordingsResponse) HasRecordings() bool {
	if o != nil && !IsNil(o.Recordings) {
		return true
	}

	return false
}

// SetRecordings gets a reference to the given []Recording and assigns it to the Recordings field.
func (o *ListRecordingsResponse) SetRecordings(v []Recording) {
	o.Recordings = v
}

func (o ListRecordingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRecordingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Recordings) {
		toSerialize["recordings"] = o.Recordings
	}
	return toSerialize, nil
}

type NullableListRecordingsResponse struct {
	value *ListRecordingsResponse
	isSet bool
}

func (v NullableListRecordingsResponse) Get() *ListRecordingsResponse {
	return v.value
}

func (v *NullableListRecordingsResponse) Set(val *ListRecordingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListRecordingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListRecordingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRecordingsResponse(val *ListRecordingsResponse) *NullableListRecordingsResponse {
	return &NullableListRecordingsResponse{value: val, isSet: true}
}

func (v NullableListRecordingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRecordingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
